- name: variables frpm prompt 
  hosts: local
  connection: local
  vars_prompt:
  - name: USERNAME
    prompt: Please enter your name
    private: true
  - name: PASSWORD
    prompt: Please enter your password
    private: true
  tasks:
  - name: print your info
    ansible.builtin.debug:
      msg: "Hello username {{USERNAME}}, password {{PASSWORD}}"