- name: variables from inventory
  hosts: local
  connection: local
  tasks:
  - name: print course info
    ansible.builtin.debug:
      msg: " Hello am learning : {{course}}, Duration is : {{Duration}}, Tariner is : {{Trainer}}"